#!/usr/bin/env python3
"""Generate the fixed SystemVerilog profile decoder from the Python policy."""

from __future__ import annotations

import argparse
from pathlib import Path

from scheduler_rtl_distilled_profiles import COMPILED_PROFILES
from scheduler_rtl_distilled_types import LOGICAL_ACTION_PRIORITY


MODE = {
    "TERMINAL": "DIST_MODE_TERMINAL",
    "SYNC": "DIST_MODE_SYNC",
    "ONE_IDLE": "DIST_MODE_ONE_IDLE",
}
FAMILY = {
    "SINGLE": "DIST_FAMILY_SINGLE",
    "PAIR": "DIST_FAMILY_PAIR",
    "SPLIT": "DIST_FAMILY_SPLIT",
}
SHAPE = {
    "NONE": "SHAPE_C",
    "A(M8,bw32)": "SHAPE_A",
    "B(M4,bw64)": "SHAPE_B",
    "C(M2,bw128)": "SHAPE_C",
}
DMA = {name: f"DMA_{name}" for name in ("NONE", "IDMA", "XDMA", "BOTH")}


def logical_id(token) -> int:
    key = (
        token.logical.mode,
        token.logical.family,
        token.logical.selectors,
        token.logical.split_rule,
    )
    return LOGICAL_ACTION_PRIORITY[key]


def emit_case(address: int, slot: int, token, logical_last: bool) -> list[str]:
    logical = token.logical
    physical = token.physical
    selectors = list(logical.selectors) + [logical.selectors[0]]
    fields = {
        "profile_slot": f"5'd{slot}",
        "logical_id": f"3'd{logical_id(token)}",
        "logical_last": f"1'b{int(logical_last)}",
        "family": FAMILY[logical.family],
        "selector_a": f"DIST_SEL_{selectors[0]}",
        "selector_b": f"DIST_SEL_{selectors[1]}",
        "split_balanced": "1'b1" if logical.split_rule == "BALANCED" else "1'b0",
        "c2_active": "1'b0" if physical.c2_s1 == "NONE" else "1'b1",
        "c3_active": "1'b0" if physical.c3_s1 == "NONE" else "1'b1",
        "c2_shape_s1": SHAPE[physical.c2_s1],
        "c2_shape_s3": SHAPE[physical.c2_s3],
        "c3_shape_s1": SHAPE[physical.c3_s1],
        "c3_shape_s3": SHAPE[physical.c3_s3],
        "c2_dma_s1": DMA[physical.c2_dma_s1],
        "c2_dma_s3": DMA[physical.c2_dma_s3],
        "c2_s2pf": DMA[physical.c2_s2pf],
        "c3_dma_s1": DMA[physical.c3_dma_s1],
        "c3_dma_s3": DMA[physical.c3_dma_s3],
        "c3_s2pf": DMA[physical.c3_s2pf],
    }
    lines = [f"      5'd{address}: begin"]
    for name, value in fields.items():
        lines.append(f"        profile_o.{name} = {value};")
    lines.append("      end")
    return lines


def generate() -> str:
    slots_by_mode = {
        mode: sorted(
            (slot for slot, token in enumerate(COMPILED_PROFILES)
             if token.logical.mode == mode),
            key=lambda slot: (logical_id(COMPILED_PROFILES[slot]), slot),
        )
        for mode in MODE
    }
    logical_last_slots = {
        slots[index]
        for slots in slots_by_mode.values()
        for index in range(len(slots))
        if index + 1 == len(slots)
        or logical_id(COMPILED_PROFILES[slots[index]])
        != logical_id(COMPILED_PROFILES[slots[index + 1]])
    }
    lines = [
        "// Generated by Idea_Model/gen_scheduler_rtl_distilled_profiles_sv.py.",
        "// Do not hand-edit; scheduler_rtl_distilled_profiles.py is normative.",
        "",
        "import sched_pkg::*;",
        "import sched_distilled_pkg::*;",
        "",
        "module sched_distilled_profile_decode (",
        "  input  logic [4:0]      profile_addr_i,",
        "  output distilled_profile_t profile_o",
        ");",
        "",
        "  always_comb begin",
        "    profile_o = '0;",
        "    profile_o.profile_slot = 5'h1f;",
        "    unique case (profile_addr_i)",
    ]
    address = 0
    for mode in ("TERMINAL", "SYNC", "ONE_IDLE"):
        for slot in slots_by_mode[mode]:
            lines.extend(emit_case(
                address, slot, COMPILED_PROFILES[slot],
                slot in logical_last_slots,
            ))
            address += 1
    lines.extend([
        "      default: profile_o.profile_slot = 5'h1f;",
        "    endcase",
        "  end",
        "",
        "endmodule",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    text = generate()
    if args.output is None:
        print(text, end="")
    else:
        args.output.write_text(text, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
