"""Block-major N-outer execution, lowering, and replay contract."""

from .model import (
    ContractConfig,
    DmaMask,
    DmaPolicy,
    ExpertSlice,
    GroupPlan,
    ItemKey,
    LoadEvent,
    NOuterSimulator,
    Phase,
    PhaseSpec,
    SchedulePlan,
    ScheduleResult,
    SlotPlan,
    TICK_CC,
    WorkItem,
    build_streams,
    build_schedule_streams,
    schedule_group,
    schedule_plan,
    slices_from_counts,
    validate_schedule,
)
from .lowering import (
    LoweredContract,
    StaticRunnerProgram,
    lower_group,
    lower_schedule_plan,
)
from .replay import ReplayResult, replay_static_runner
from .protocol import (
    DMA_POLICY_VERSION,
    PROTOCOL_VERSION,
    REQUIRED_FLAGS,
    SchedulerWordStream,
    decode_scheduler_words,
    emit_scheduler_words,
)
from .runtime_interface import (
    NOuterWorkerArgs,
    RuntimeLayout,
    RuntimeScheduleTables,
    WorkerRole,
    decode_runtime_tables,
    lower_runtime_tables,
)

__all__ = [
    "ContractConfig",
    "DmaMask",
    "DmaPolicy",
    "DMA_POLICY_VERSION",
    "ExpertSlice",
    "GroupPlan",
    "ItemKey",
    "LoadEvent",
    "LoweredContract",
    "NOuterSimulator",
    "NOuterWorkerArgs",
    "Phase",
    "PhaseSpec",
    "PROTOCOL_VERSION",
    "REQUIRED_FLAGS",
    "ReplayResult",
    "ScheduleResult",
    "SchedulePlan",
    "SlotPlan",
    "SchedulerWordStream",
    "StaticRunnerProgram",
    "TICK_CC",
    "WorkItem",
    "WorkerRole",
    "build_streams",
    "build_schedule_streams",
    "decode_runtime_tables",
    "decode_scheduler_words",
    "emit_scheduler_words",
    "lower_group",
    "lower_schedule_plan",
    "lower_runtime_tables",
    "replay_static_runner",
    "RuntimeLayout",
    "RuntimeScheduleTables",
    "schedule_group",
    "schedule_plan",
    "slices_from_counts",
    "validate_schedule",
]
