"""Block-major N-outer execution, lowering, and replay contract."""

from .model import (
    ContractConfig,
    DmaMask,
    DmaPolicy,
    ExpertSlice,
    GroupPlan,
    ItemKey,
    LoadEvent,
    NOuterSimulator,
    Phase,
    PhaseSpec,
    ScheduleResult,
    TICK_CC,
    WorkItem,
    build_streams,
    schedule_group,
    slices_from_counts,
    validate_schedule,
)
from .lowering import (
    LoweredContract,
    RtlGroupImage,
    RtlGroupRecord,
    StaticRunnerProgram,
    decode_rtl_group,
    emit_rtl_group,
    lower_group,
    pack_rtl_record,
    unpack_rtl_record,
)
from .replay import ReplayResult, replay_static_runner

__all__ = [
    "ContractConfig",
    "DmaMask",
    "DmaPolicy",
    "ExpertSlice",
    "GroupPlan",
    "ItemKey",
    "LoadEvent",
    "LoweredContract",
    "NOuterSimulator",
    "Phase",
    "PhaseSpec",
    "ReplayResult",
    "RtlGroupImage",
    "RtlGroupRecord",
    "ScheduleResult",
    "StaticRunnerProgram",
    "TICK_CC",
    "WorkItem",
    "build_streams",
    "decode_rtl_group",
    "emit_rtl_group",
    "lower_group",
    "pack_rtl_record",
    "replay_static_runner",
    "schedule_group",
    "slices_from_counts",
    "validate_schedule",
    "unpack_rtl_record",
]
